rules:
  decks: 8
  penetration: 0.50
  dealer_hits_soft_17: true
  blackjack_payout: "3:2"
  split_limit: 1
  double_after_split: true
  surrender: "none"
  peek: true
  insurance_payout: "2:1"

run:
  hands: 100000
  seed: 123456
  cache_clear_every: 500    # <— clear caches every 200 hands
  logs:
    audit_every: 1
    trace_sample_rate: 0.0

paths:
  results_dir: "results"
